### ISSUE TITLE
通知欄に表示されないものがある？

### ISSUE THREAD

**Issue by ShinoharaTa** [hota1024/ucho-ten#27]
## 不具合の概要

一部の通知に取得しているのか、枠のみが表示されている状態です
内部のコンテンツ取得に失敗？

## 該当箇所のスクショ等

![image](https://user-images.githubusercontent.com/23314412/234535480-56b75d95-a360-41c9-908b-3596952e572b.png)

## 補足事項など

特になし

**Comment by toei-zenritsu-line** [comment]
@ShinoharaTa さん
現状、リポストの通知は非表示にしていて、こちらで検証したところ、やはりリポストの枠組みだけは消えていなかったようです。
修正いたします！

**Comment by toei-zenritsu-line** [comment]
488ad25dc66a4cb64cf3c94c3865d914751ea994

修正したためcloseいたします
