### ISSUE TITLE
getTimelineのタイミング調整

### ISSUE THREAD

**Issue by ShinoharaTa** [hota1024/ucho-ten#28]
こちらはサーバー負荷をある程度下げるためにも公式(staging.bsky.app)に合わせて、15秒を基準としたほうがいいかもしれません

**Comment by hota1024** [comment]
@ShinoharaTa 確かに公式に合わせた方が良さそうですね。
次のデプロイで修正されます～
dd7d7552c77b65afed00a7fc0fc1e510467bab55

**Comment by toei-zenritsu-line** [comment]
こちらはすでにmasterにてデプロイ済みであるため、closeいたします。
