### ISSUE TITLE
ふぁぼ連打で500 Internal Server Errorが頻発

### ISSUE THREAD

**Issue by ShinoharaTa** [hota1024/ucho-ten#32]
## 不具合の概要

ふぁぼを連打すると500 Internal Server Errorが頻発する
そのため画面の状態と、じっさいのふぁぼ状態が一致しないこととなる

## 補足事項など

アクション中はふぁぼボタンを非活性にするなどの対応を検討

**Comment by toei-zenritsu-line** [comment]
@ShinoharaTa さん
e8bf20b998300bcdb8c15f2e5f1e318c9d75839d
先ほどこの問題を以上にて修正しました。

ご報告ありがとうございました！
