### ISSUE TITLE
リプライツリーが3つ以上連続しても表示がつながらない

### ISSUE THREAD

**Issue by kawarimidoll** [hota1024/ucho-ten#33]
## 不具合の概要
投稿に対するリプライが連続すると、実際の話の流れと表示上の順序が前後してしまいます

## 該当箇所のスクショ等
![SCR-20230426-qrau](https://user-images.githubusercontent.com/8146876/234544250-7afafe51-ff9a-4dce-a087-0db216746a9f.png)

## 補足事項など
プロフィールページにて確認

**Comment by kawaikute-gomen** [comment]
@kawarimidoll さん

2週間ほど前に修正しましたのでクローズいたします。
この度はフィードバックありがとうございました！
