### ISSUE TITLE
feature request: 絵文字入力欄

### ISSUE THREAD

**Issue by kawarimidoll** [hota1024/ucho-ten#34]
mustではなくwantですが、投稿欄で絵文字を選択・入力できると良いと思いました

**Comment by toei-zenritsu-line** [comment]
@kawarimidoll さん
次回のデプロイにてemoji-pickerが導入されます！
ご要望ありがとうございました！

**Comment by kawarimidoll** [comment]
Thank you 🙌  🥳 
<img width="442" alt="image" src="https://user-images.githubusercontent.com/8146876/236678095-9daaef60-c6e2-4143-afcc-e85355537c81.png">
