### ISSUE TITLE
URLのID(#)がリンクになっていない

### ISSUE THREAD

**Issue by kawarimidoll** [hota1024/ucho-ten#38]
## 不具合の概要
URLにID(`#xxx...`)が含まれている場合に、その手前でリンクが途切れてしまっています

## 該当箇所のスクショ等
![SCR-20230426-ssca](https://user-images.githubusercontent.com/8146876/234576767-93276ad8-d60c-45cb-95de-5bbedd6b5ecb.png)

## 補足事項など
表示だけでなく、実際に遷移してもID指定が効いていないことを確認しました

**Comment by toei-zenritsu-line** [comment]
取り急ぎ修正いたしました。
ご報告ありがとうございます！

**Comment by kawarimidoll** [comment]
ありがとうございます 🙌 
![image](https://user-images.githubusercontent.com/8146876/234771039-fd6ef573-b8ba-47a8-ac54-21ec9d076407.png)
